
--[[
Copyright (C) 2016 DBot

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
]]

local en = {
	scvar_base = '%s\n\nConVar: dpp_%s',
	model = 'Model',
	add_model = 'Add model',
	remove_model = 'Remove model',
	action_looking_at = '%s of entity you are looking at',
	visual_list = 'Open visual list',
	apply = 'Apply',
	discard = 'Discard',
	modifying = 'Modifying %s',
	sharing = 'Share settings of %s',
	unshare = 'Uncheck all and apply',
	
	remove_my_ents = 'Remove entities owned by me',
	display_customization_color = 'Display colours customization',
	display_customization = 'Display customization',
	display_x = 'X coordinate (percent) on screen for owner display',
	display_y = 'Y coordinate (percent) on screen for owner display',
	
	clear_decals = 'Clear decals',
	report_ents = 'Collect and print info about entities',
	delete_ents = 'Delete all player owned entities',
	
	freeze_all = 'Freeze all player owned entities',
	freeze_all_phys = 'Freeze all valid physics objects',
	delete_disconnected = 'Delete entities owned by disconnected players',
	action_unfreeze = 'UF',
	action_freeze = 'F',
	action_delete = 'D',
	fallback_select = 'Selected player: %s\nSteamID: %s',
	fallback_select_none = 'Selected player: None\n',
	owning_fallback = 'This page is "owning fallback"\nWhen you disconnect from server, DPP will assign\nownership of all entities owned by you to selected player.',
	owning_fallback_r = 'Unselect player',
	disable_protection_for = 'Disable %q protection module for %s',
	clipboard = 'Copy %s to clipboard',
	model_path = 'model path',
	Unblock = 'Unblock',
	model_blacklist = 'Model blacklist',
	model_blacklist_2 = 'Model blacklist. To open menu of model, click on model icon.',
	Resizeable = 'Window can be resized',
	click_reset = 'Click here to reset window size',
	remove_from_blacklist = 'Remove from blacklist',
	Class = 'Class',
	Group = 'Group',
	Groups = 'Groups',
	Limit = 'Limit',
	Entity = 'Entity',
	tool_mode = 'tool mode',
	add_tool_mode = 'Add tool mode',
	remove_tool_mode = 'Remove tool mode',
	property_types_edit = 'DPP Property Types Edit',
	add_to_all_blacklists = 'Add that entity to ALL blacklists',
	add_to_all_blacklists_this = 'Add this entity to ALL blacklists',
	remove_from_all_blacklists = 'Remove that entity from ALL blacklists',
	remove_from_all_blacklists_this = 'Remove this entity from ALL blacklists',
	edit_limit = 'Add/Edit limit',
	edit_limit_a = 'Add/Edit/Remove limit',
	edit_limit_e = 'Edit limit...',
	remove_limit = 'Remove limit',
	remove_limit_all = 'Remove this limit from all groups',
	entity_limit_note = 'NOTE: This just prevents the player from spawning\n entities with the given class if the player spawned\n the given amount of entities within this class.\nThat means it DOES NOT allow groups to spawn\n unlimited amounts of entities within that\n type. For that use the Sandbox limits\n instead.',
	limit_tip = 'Unlimited: -1\n0 - removes limit from db\nAny values higher than 0 is a limit',
	elimit_tip = '-1 - removes limit from db\nAny values higher than 0 is a limit',
	sbox_limit_note = 'WHAT THIS DOES:\nIt\'s the console variable sbox_max<...> overrides for user groups.\nTo add values, you must know the console variable you are changing.\nExample: Modifying prop limits would be "props" (sbox_maxprops).\nA value of -1 is unlimited, and 0 leaves the limit unmodified.',
	constraints_limit_tip = 'You can see type of constraints in DPP logs\nATTENTION: Because of nature of rope constraints\nDPP thinks that keyframe_rope is a "vrope"\nconstraint because rope (and related) constraints\n creating keyframe_rope too to show visual rope.',
	sbox_max = 'sbox_max...',
	remove_from_restrict_list = 'Remove from restriction list',
	modify_r = 'Modify...',
	add_r = 'Add...',
	edit_r = 'Edit...',
	remove_friend = 'Remove player from friend list',
	add_friend = 'Add %s to friend list',
	nick = 'Nick',
	steamid = 'SteamID',
	add_steamid = 'Add player by SteamID',
	cvar_name = 'console variable name',
	add_entity = 'Add entity',
	remove_entity = 'Remove entity',
	add_blacklist_looking_at = 'Add the entity you are looking at to the blacklist',
	add_blacklist_looking_at_all = 'Add the entity you are looking at to ALL blacklists',
	remove_blacklist_looking_at = 'Remove the entity you are looking from the blacklist',
	remove_blacklist_looking_at_all = 'Remove the entity you are looking from ALL blacklists',
	is_white = 'Is whitelist',
	about_header = 'DPP - DBot Prop Protection, by DBot.\nI tried to make it situable for all kinds of servers\nthat needs protect from minges',
	about_thumbup = 'Can we have a free like please?\nPlease?! or i will cry ;n;',
	about_star = 'Can we have a free star please?\nPlease?! or i will cry ;n;',
	about_bug = 'Can we have a free bug report please?\nPlease?!',
	about_issues = 'DPP issues page',
	display_customization_colors = 'Display colours customization',
	
	remove_exclude = 'Remove from exclude list',
	add_exclude_all = 'Add that entity to ALL exclude lists',
	remove_exclude_all = 'Remove that entity from ALL exclude lists',
	
	add_exclude_looking_at = 'Add the entity you are looking at to the exclude list',
	add_exclude_looking_at_all = 'Add the entity you are looking at to ALL exclude lists',
	remove_exclude_looking_at = 'Remove the entity you are looking at from the exclude list',
	remove_exclude_looking_at_all = 'Remove the entity you are looking at from ALL exclude lists',
	
	toolmode_exclude_tip = [[
This list defines toolgun modes that is allowed to be 
used on ANY entity. For example, if you add "remover" 
there, anyone can remove any entity using remover toolgun.
REMEMBER: Blacklists are ALWAYS have higher priority
than other lists! That means excluded tool modes
can NOT be used on blacklisted from toolgun entities.
]],
	exclude_tip = [[
Entities what listed there will have
%q protection disabled. It means that
ANYONE able to touch that entitiy despite of it's owner
REMEMBER: Blacklists are ALWAYS have higher priority
than other lists! That means blacklist will override
any whitelist!
]],

	property_exclude_tip = [[
This list defines property types that is allowed to be 
used on ANY entity. For example, if you add "remover" 
there,  anyone can remove any entity using property menus. 
To see all property classes, type use button below.
REMEMBER: Blacklists are ALWAYS have higher priority
than other lists! That means excluded property
modes can NOT be used on blacklisted toolgun
entities.
]],

	properties_list = 'Open properties list...',
	property_class = 'Property Class',
	add_property = 'Add Property',
	remove_property = 'Remove Property',
	tool_exclude = '\nNOTE FOR TOOLGUN: "remover" still can\'t be used\non whitelisted entities.',
	
	--Core messages
	model_is_blacklisted = 'Model is in the blacklist',
	is_shared = 'Shared %s',
	is_shared_e = 'Shared by owner',
	not_a_owner_pp = 'Not owned by you/constrained',
	not_a_owner = 'Not a owner',
	world_pp = 'Belong/Constrained to world',
	dpp_no_touch_true = 'dpp_no_touch is TRUE!',
	dpp_no_touch_world = 'dpp_no_touch_world is TRUE!',
	protection_disabled_owner = 'Owner disabled %s protection',
	dpp_no_touch_other = 'dpp_no_touch_other is TRUE!',
	protection_disabled = 'Protection is disabled',
	World = 'World',
	not_valid = 'Invalid entity',
	props_cleared = "%s's props has been cleaned up",
	props_up_for_grabs = "%s's props is now up for grabs!",
	disconnected_player = 'Disconnected player',
	up_for_grabs = 'Up for grabs!',
	
	--Hooks messages
	owned_by_world = 'Owned by world',
	no_toolgun_player = 'Player toolgun is disabled',
	entity_excluded = 'Entity is excluded',
	entity_excluded_d = 'Damage allowed (entity is excluded)',
	toolmode_excluded = 'Tool mode is excluded',
	toolmode_blocked_world = 'Toolgun mode on world is in the blacklist',
	toolgun_blocked = 'Entity is in the blacklist',
	no_rope_world = 'No rope world',
	restricted_tool = 'Toolgun mode is restricted',
	vehicle_protection_ignored = 'Vehicle ignores protection',
	dpp_property = 'DPP Property',
	property_restricted = 'Property is restricted',
	property_excluded = 'Property is excluded',
	use_blocked = 'Entity is in the blacklist',
	gravgun_blocked = 'Entity is in the blacklist',
	physgun_blocked = 'Entity is in the blacklist',
	toolgun_antispam = 'Toolgun spam',
	damage_allowed = 'Damage allowed',
	damage_blocked = 'Damage blocked',
	
	e2adv_func_restricted_s = '(SERVERSIDE) DPP: Function is restricted: %s()',
	e2adv_func_restricted = 'DPP: Function is restricted: %s()',
	
	--Server hooks messages
	unable_to_unfreeze = 'Unable to unfreeze: You are trying un freeze %s entities at once (%s max)!',
	physgun_reload_disabled = 'Physgun unfreeze is disabled on this server',
	physgun_reload_wait = 'You must wait %s seconds before trying to unfreeze again',
	
	e2_func_restricted = 'DPP: Function is restricted: %s()',
	spam_removed = 'Prop is removed due to spam',
	spam_ghosted = 'Prop is ghosted due to spam',
	
	vehicle_restricted = 'Vehicle is restricted',
	model_restricted = 'Model is restricted',
	weapon_restricted = 'Weapon is restricted',
	npc_restricted = 'NPC is restricted',
	entity_restricted = 'Entity is restricted',
	entity_limit_hit = 'You hit %q limit!',
	
	--Serverside functions
	ghosted_big = 'Prop is ghosted because it is too big.',
	prop_autoban = 'Prop is too big for ya.',
	stuck_hit = 'It seems that this prop is stuck in another.',
	grabs_hit = 'You now own this prop',
	
	--Report
	report_summary = '------------ SUMMARY',
	report_owners = '------------ OWNERS',
	report_spawned = ' have %s entities spawned!',
	report_spawned_h = '------------ SPANWED ENTITIES ------------',
	report_allents = '------------ ALL ENTITIES ------------',
	report_allpos = '------------ ALL POSITIONS',
	report_allclass = '------------ ALL CLASSES',
	report_solidpos = '------------ SOLID POSITIONS',
	report_solidclass = '------------ SOLID CLASSES',
	report_misc = '------------ MISC',
	report_generated = '------------ REPORT GENERATED IN %s ms',
	report_envshake = 'ATTENTION! There are %s env_shake entities! Did we have entity use leak?',
	report_nodata = '<no data>',
	report_near = 'Near %s, there are ',
	report_have = ' have ',
	report_espawned = ' entities spawned!',
	report_entitites = ' entities!',
	
	report_1 = 'Total Entities on server:',
	report_2 = 'Total owned entities:',
	report_3 = 'Total unowned entities:',
	report_4 = 'Total non-solid entities:',
	report_5 = 'Total entities spawned by map:',
	report_6 = 'Total entities with physics:',
	report_7 = 'Total entities that can move:',
	report_8 = 'Total entities that is moving:',
	report_9 = 'Entities skipped:',
	
	--Logging
	log_spawned = ' spawned ',
	log_tried = ' tried ',
	log_tried_c = 'to create constraint ',
	log_tried_f = 'to use E2 function %s',
	log_to_spawn = 'to spawn',
	log_created_constraint = ' created constraint ',
	log_constraint_between = ' between %s and %s',
	log_unknown = '<unknown>',
	
	log_not_avaliable = 'N/A',
	log_npc = '(NPC)',
	log_effect = '(Effect)',
	log_prop = '(Prop)',
	log_ragdoll = '(Ragdoll)',
	log_sent = '(SENT)',
	log_swep = '(SWEP)',
	log_vehicle = '(Vehicle)',
	log_obj = '(Object/Generic)',
	
	log_tried_t = 'to use tool ',
	log_tool_used = ' used/tried to use tool ',
	log_tool_on = ' on ',
	log_tool_on_f = '%s on %s',
	
	--Commands
	com_decals = ' cleared decals',
	com_no_target = 'No valid target found',
	com_invalid_target = 'Invalid target',
	com_invalid_mode = 'Invalid mode',
	com_invalid_status = 'Invalid status',
	com_invalid_pmode = 'Invalid protection mode',
	com_invalid_uid = 'Invalid player UID',
	com_invalid_eid = 'Invalid Entity Network ID',
	com_invalid_ply_userid = 'Invalid player UserID',
	com_invalid_ply_c = 'Invalid player UserID/Nickname',
	com_invalid_share = 'Invalid share type',
	com_invalid_cvar = 'Invalid server variable',
	com_invalid_cvar_v = 'Invalid value',
	com_cleared_disconnected = ' cleared all entities owned by disconnected players',
	com_cleared_map = ' cleaned up map',
	com_cleared_ply_1 = ' cleared all ',
	com_cleared_ply_2 = "'s props",
	com_ply_ents = "'s entities",
	com_freezed_players = " freezed all player's entities",
	com_freezed = ' freezed all valid physics objects. Total frozen: %s',
	com_freezed_all = ' freezed all ',
	com_unfreezed_all = ' unfreezed all ',
	com_clear_success = 'Successfully removed entities owned by you',
	com_clear_success_c = ' cleared his props',
	com_transfer = ' transfered ownership of ',
	com_transfer_s = 'Successfully transfered ownership of entity to world',
	com_transfer_s_c = 'Successfully transfered ownership of entity and constrained entities to world',
	com_transfer_world = ' to world',
	com_transfer_world_c = ' with constrained entities to world',
	com_report_req = ' requested entities report',
	com_target = ' target ',
	com_no_props_to_transfer = 'No props to transfer',
	com_transfer_all = ' transfered ownership of all his entities to ',
	com_owning_transfer = 'Successfully transfered ownership of entity to ',
	com_owning_transfer_all = 'Successfully transfered ownership of all props to ',
	com_owning_fallback = ' as entities owner fallback',
	com_owning_fallback_m = ' now will own your props if you disconnect',
	com_owning_no = 'Already no owning fallback',
	com_owning_removed_n = 'Fallback unselected successfully',
	com_owning_removed = ' removed their owning fallback.',
	com_success = 'Success. ',
	com_fallback_triggered = 'Transfering props ownership from ',
	com_fallback_triggered_1 = 'All ',
	com_fallback_triggered_2 = ' props now belong to you.',
	com_to = ' to ',
	com_cvar_set_1 = ' set convar ',
	look_into_console = 'Look into console',
	
	--Client commands
	no_friend_with_steamid = 'There is no friend with id %s!',
	friend_removed = 'Friend %s was removed',
	friend_added = 'Friend added',
	friends_saved = 'Friend list saved...',
	friends_loaded = 'Friend list loaded...',
	friends_refreshed = 'Friend list refreshed',
	friends_sended = 'Sending friend list to server',
	
	--Property menus
	property_cleanup = 'Cleanup props of owner',
	property_share = 'Share this prop',
	property_transferworld = 'Transfer ownership to world',
	property_transferplayer = 'Transfer ownership to a player...',
	property_roptions = 'DPP Restrict options',
	property_add_blocked_models = 'Add to DPP model blacklist',
	property_remove_blocked_models = 'Remove from DPP model blacklist',
	property_add_blacklist = 'Add to %q DPP blacklist',
	property_remove_blacklist = 'Remove from %q DPP blacklist',
	property_add_restrict = 'Add to %q DPP restrictions list',
	property_remove_restrict = 'Remove from %q DPP restrictions list',
	property_modify_restrict = 'Modify DPP %q restriction...',
	
	--Misc messages
	prop_stuck_in_player = 'It seems that this prop is stuck in someone',
	net_must_wait = 'You must wait before request full network pocket again!',
	net_manual = ' requested full network update manually',
	net_auto = ' requested full network update automatically',
	net_error_1 = 'Oh no! Something went terribly wrong! i am unable to send data to client. The error message follows:',
	net_error_2 = 'If you thinks this is DPP problem, report on BitBucket and tell how did you got this.',
	accepted = 'Accepted',
	saving_cvars = 'Saving console variables into database...',
	
	--Tool menu
	menu_server = 'Server Variables',
	menu_server2 = 'Secondary Server Variables',
	menu_propkill = 'Anti-Propkill',
	menu_client = 'Client options',
	menu_antispam = 'Antispam options',
	menu_elimits = 'Entity limits',
	menu_slimits = 'Sandbox limits',
	menu_climits = 'Constraints limits',
	menu_mblacklist = 'Model blacklist',
	menu_friends = 'Friends',
	menu_players = 'Player Controls',
	menu_pcontrols = 'Player protection controls',
	menu_about = 'About',
	menu_fallback = 'Fallback and transfer',
	menu_blacklist = '%s blacklist',
	menu_exclude = '%s exclude list',
	menu_restricts = '%s Restrictions',
	
	menu_tool = 'Tool',
	menu_physgun = 'Physgun',
	menu_use = 'Use',
	menu_damage = 'Damage',
	menu_gravgun = 'Gravgun',
	menu_pickup = 'Pickup',
	menu_toolworld = 'Toolgun World',
	menu_toolmode = 'Toolgun Mode',
	menu_sent = 'SENT',
	menu_vehicle = 'Vehicle',
	menu_swep = 'SWEP',
	menu_model = 'Model',
	menu_npc = 'NPC',
	menu_property = 'Property',
	menu_propertyt = 'Property Class',
	menu_pickup = 'Pickups',
	menu_e2function = 'E2 Functions',
	menu_e2afunction = 'E2 Advanced Functions',
	
	menu_main = 'Main options',
	menu_blacklists = 'Blacklists',
	menu_exclude_lists = 'Exclude lists',
	menu_restrictions = 'Restrictions',
	menu_restrictions_ply = 'Restrictions per SteamID',
	
	menu_set_fallbackto = 'Set Fallback to %s',
	menu_transferto = 'Transfer ownership of ALL props to %s',
	
	menu_player_tip = 'Player nickname: %s\nPlayer SteamID: %s\nPlayer SteamID64: %s\nIs your friend: %s',
	menu_player_list_tip = 'Player nickname: %s\nPlayer SteamID: %s\nPlayer SteamID64: %s',
	steam_profile = 'Steam profile',
	open = 'Open %s',
	quick_search = 'Quick search by nickname',
	search_placeholder = 'Search...',
	
	--Some texts
	main_note = 'DPP was created by DBot\nNOTE "Main Power Switch" disables blacklists \nand protection modules, but not restrictions.',
	strict_property_note = [[
ATTENTION: THIS REPLACES PROCESSING OF PROPERTY NET MESSAGE
AND ENABLES STRICT CHECKS FOR ENTITIES
SOME NON-DEFAULT PROPERTIES MAY BREAK
IT WILL DISALLOW TO USE PROPERTIES
EVEN IF THEY "TALK" THAT THEY ARE ALLOWED
TO BE USE ON THAT ENTITY.\nUSE WITH CAUTION
(this may cover possible exploits with non-default properties)
]],

	givechance_error = 'ATTENTION! ENTITY THROW EXCEPTION. ',
	givechance_Entity = 'Entity ',
	givechance_desc = ' THROW NEXT EXCPETION WHILE CALLING %q FUNCTION: ',
	givechance_returned = 'Entity controls protection by itself',
	
	Console = 'Server',
	request_net_update = 'Request DPP network refresh',
	
	--Manipulation commands
	saveload_added = ' added ',
	saveload_removed = ' removed ',
	saveload_to = ' to ',
	saveload_from = ' from ',
	saveload_bmodels = 'model blacklist/whitelist',
	saveload_invalid_model = 'Invalid model',
	saveload_invalid_class = 'Invalid entity class',
	saveload_invalid_group = 'Invalid group',
	saveload_invalid_limit = 'Invalid limit value',
	saveload_invalid_slimit = 'Invalid sandbox limit variable',
	saveload_invalid_climit = 'Invalid constraint name',
	saveload_model_already_y = 'Model already blocked',
	saveload_entity_already_y = 'Entity is already listed in that blacklist',
	saveload_eentity_already_y = 'Entity is already listed in that exclude list',
	saveload_model_already_n = 'Model is not blocked',
	saveload_entity_already_n = 'Entity is not listed in that blacklist',
	saveload_eentity_already_n = 'Entity is not listed in that exclude list',
	saveload_unable_to_add = 'You can not add that entity to blacklist',
	saveload_unable_to_remove = 'You can not remove that entity to blacklist',
	saveload_blackwhite = ' blacklist/whitelist',
	saveload_excludedents = ' excluded entities',
	saveload_restricted = 'restricted ',
	saveload_added_updated = ' added/updated ',
	saveload_limit_removed = ' from limits list for ',
	saveload_limits = ' limits for ',
	saveload_slimits = ' sbox limits list for ',
	saveload_climits = ' constraint limit list for ',
	saveload_limit_not_exists = 'Limit for class does not exists',
	
	saveload_command_message_1 = 'Invalid class to restrict (#1)',
	saveload_command_message_2 = 'Invalid group(s). Groups are seperated by comma, without spaces (#2)',
	saveload_command_message_2ply = 'Invalid SteamID (#2)',
	saveload_command_message_3 = 'Invalid argument "is white list" (#3)',
	saveload_command_message_4 = 'Invalid class to unrestrict',
	
	menu_misc_moved = 'Generic options was moved to "Utilities" panel',
	utilities = 'Utilities',
	
	inspect_button = 'Inspect entity you are looking at',
	inspect_client = '--CLIENT--',
	inspect_server = '--SERVER--',
	inspect_class = 'Entity Class: ',
	inspect_pos = 'Entity Position: ',
	inspect_ang = 'Entity Angles: ',
	inspect_hp = 'Entity Health: ',
	inspect_mhp = 'Entity Max Health: ',
	inspect_owner = 'Entity owner: ',
	inspect_model = 'Entity model: ',
	inspect_skin = 'Entity skin: ',
	inspect_bodygroups = 'Entity bodygroup count: ',
	inspect_table = 'Entity values in :GetTable() :',
	inspect_noentity = 'Entity is not valid',
	
	restricts_updated = '(SILENT) You updated restricts for %s',
	
	font = 'Font',
	cust_display_background = 'Owner display background color',
	cust_display_can = 'Color when can touch',
	cust_display_cant = 'Color when can not touch',
	display_customization_position = 'Owner display position',
	
	friend_buddy = 'Friend in %q protection',
	share_type = 'Share in %q protection module',
	
	crazy_physics = 'Crazy physics detected, next prop have crazy physics: ',
	crazy_physics2 = ' that belongs to ',
	crazy_physics3 = ', ghosting it.',
	
	cami_tip = "Can't find your custom group here?\nYou can enter a custom one here!\n(that happens if admin mod doesn't support CAMI\nor it's CAMI support is bad)",
	
	plyrestrict_already_not_restricted = 'This is not restricted from that player!',
	plyrestrict_already_restricted = 'This is already restricted from that player!',
	plyrestrict_from = ' from SteamID ',
	selecting_player = 'Select a player...',
	remove_r = 'Remove restriction',
	
	saveload_command_message_1ply = 'Invalid SteamID (#1)',
	saveload_command_message_2ply = 'Invalid Class (#2)',
}

local ru = {
	--Added in phrases testing
	scvar_base = '%s\n\nКонсольная переменная: dpp_%s',
	model = 'Модель',
	add_model = 'Добавить модель',
	remove_model = 'Удалить модель',
	action_looking_at = '%s от энтити на которые Вы смотрите',
	visual_list = 'Открыть графическое представление',
	apply = 'Применить',
	discard = 'Отмена',
	modifying = 'Изменение %s',
	
	--Console Variables
	cvar_admin_can_everything = 'Админы могут трогать энтити других игроков',
	cvar_advanced_spawn_checks = 'Улучшенные проверки создания (для WAC Aircraft, SCars, т.д.)',
	cvar_allow_damage_npc = 'Всегда разрешать наносить урон NPC',
	cvar_allow_damage_sent = 'Всегда разрешать наносить урон SENTs других игроков',
	cvar_allow_damage_vehicles = 'Всегда разрешать наносить урон транспорту',
	cvar_antispam = 'Предотвращать спам',
	cvar_antispam_cooldown_divider = 'Ниже - более быстрый счётчик сброса',
	cvar_antispam_delay = 'Минимальная задержка между созданием энтити',
	cvar_antispam_ghost = 'Предел спама для начала гхостинга',
	cvar_antispam_max = 'Предел счётчика (максимальное значение таймера)',
	cvar_antispam_remove = 'Предела спама для начала удаления энтити',
	cvar_antispam_toolgun = 'Минимальная задержка между использованиями инструмента',
	cvar_antispam_toolgun_enable = 'Включить антиспам инструментом',
	cvar_apanti_disable = 'Отключить APAnti гхостинг',
	cvar_apropkill_clampspeed = 'Уменьшать максимальную скорость физпушки',
	cvar_apropkill_clampspeed_val = 'Значение уменьшения. Изменяйте на свой риск!',
	cvar_apropkill_damage = 'Анти-Пропкилл',
	cvar_apropkill_damage_noworld = 'Энтити без владельца обходят проверку на урон',
	cvar_apropkill_damage_vehicle = 'Отключить коллюзии у транспорта',
	cvar_apropkill_enable = 'Включить Анти-Пропкилл',
	cvar_apropkill_nopush = 'Анти-Проп пуш',
	cvar_apropkill_nopush_mode = 'False - только коллюзии с игроком, True - ВСЕ коллюзии',
	cvar_apropkill_vehicle = 'Отключить коллюзии транспорта',
	cvar_blacklist_damage = 'Включить чёрный список урона',
	cvar_blacklist_damage_admin_can = 'Могут ли админы наносить урон энтити из чёрного списка?',
	cvar_blacklist_damage_player_can = 'Могут ли игроки наносить урон энтити из чёрного списка?',
	cvar_blacklist_damage_white = 'Чёрный лист урона является белым списком.',
	cvar_blacklist_gravgun = 'Enable Gravgun blacklist',
	cvar_blacklist_gravgun_admin_can = 'Могут ли админы трогать энтити из чёрного списка?',
	cvar_blacklist_gravgun_player_can = 'Могут ли игроки трогать энтити из чёрного списка?',
	cvar_blacklist_gravgun_white = 'Чёрный лист гравипушки является белым списком.',
	cvar_blacklist_physgun = 'Enable Physgun blacklist',
	cvar_blacklist_physgun_admin_can = 'Могут ли админы трогать энтити из чёрного списка?',
	cvar_blacklist_physgun_player_can = 'Могут ли админы трогать энтити из чёрного списка?',
	cvar_blacklist_physgun_white = 'Чёрный лист физпушки является белым списком.',
	cvar_blacklist_pickup = 'Включить чёрный лист подбираемых',
	cvar_blacklist_pickup_admin_can = 'Могут ли админы подбирать энтити из чёрного списка?',
	cvar_blacklist_pickup_player_can = 'Могут ли игроки подбирать энтити из чёрного списка?',
	cvar_blacklist_pickup_white = 'Чёрный лист подбираемых является белым списком.',
	cvar_blacklist_tool = 'Включить чёрный список инструмента',
	cvar_blacklist_tool_admin_can = 'Могут ли админы использовать инструмент на энтити из чёрного списка?',
	cvar_blacklist_tool_player_can = 'Могут ли игроки использовать инструмент на энтити из чёрного списка?',
	cvar_blacklist_tool_white = 'Чёрный лист инструмента является белым списком.',
	cvar_blacklist_toolworld = 'Включить чёрный список режима инструмента по миру',
	cvar_blacklist_toolworld_admin_can = 'Могут ли админы обходить данный список?',
	cvar_blacklist_toolworld_player_can = 'Могут ли игроки обходить данный список?',
	cvar_blacklist_toolworld_white = 'Чёрный лист режима инструмента по миру является белым списком.',
	cvar_blacklist_use = 'Включить чёрный лист используемых',
	cvar_blacklist_use_admin_can = 'Могут ли админы трогать энтити из чёрного списка?',
	cvar_blacklist_use_player_can = 'Могут ли игроки трогать энтити из чёрного списка?',
	cvar_blacklist_use_white = 'Чёрный лист используемых работает как белый лист.',
	cvar_can_admin_physblocked = 'Могут ли админы использовать физпушку на заблокированных энтити',
	cvar_can_admin_touch_world = 'Могут ли админы трогать энтити без владельца',
	cvar_can_touch_world = 'Могут ли игроки трогать энтити без владельца',
	cvar_check_sizes = 'Проверять размеры энтити',
	cvar_check_stuck = 'Предотвращать застревания пропа в пропе',
	cvar_clear_disconnected = 'Очищать энтити отключившихся игроков',
	cvar_clear_disconnected_admin = 'Очищать энтити отключившихся админов',
	cvar_clear_timer = 'Таймер очистки, в секундах',
	cvar_const_limits_enable = 'Включить лимит соединений',
	cvar_disable_damage_world = 'Отключить защиту от урона на энтити без владельца',
	cvar_disable_gravgun_world = 'Отключить защиту от гравипушки на энтити без владельца',
	cvar_disable_pickup_world = 'Отключить защиту подбираемых энтити без владельца',
	cvar_disable_unfreeze = 'Отключить разморозку физпушкой (Перезарядка)',
	cvar_disable_use_world = 'Отключить защиту используемых энтити без владельца',
	cvar_disable_veh_world = 'Отключить защиту транспорта без владельца',
	cvar_disconnect_freeze = 'Замораживать энтити игроков при его отключении',
	cvar_echo_spawns = 'Выводить журнал создания в консоль',
	cvar_enable = 'Главный рубильник (Включает защиту)',
	cvar_enable_blocked = 'Включить черные листы',
	cvar_enable_damage = 'Включить защиту от урона',
	cvar_enable_drive = 'Включить защиту от управления энтити',
	cvar_enable_gravgun = 'Включить защиту гравипушки',
	cvar_enable_lists = 'Включить листы ограничений',
	cvar_enable_physgun = 'Включить защиту физпушки',
	cvar_enable_pickup = 'Включить защиту подбираемых',
	cvar_enable_tool = 'Включить защиту инструмента',
	cvar_enable_use = 'Включить защиту используемых',
	cvar_enable_veh = 'Включить защиту транспорта',
	cvar_enable_whitelisted = 'Включить листы исключений',
	cvar_ent_limits_enable = 'Включить лист ограничений по энтити',
	cvar_experemental_spawn_checks = 'Эксперементальные проверки спавна',
	cvar_freeze_on_disconnect = 'Замораживать энтити игроков при его отключении',
	cvar_grabs_disconnected = 'Включить возможность присвоения энтити отключившихся игроков',
	cvar_grabs_disconnected_admin = 'Включить возможность присвоения энтити отключившихся админов',
	cvar_grabs_timer = 'Таймер активации присвоения, в секундах',
	cvar_log_constraints = 'Должны ли соединения журналироватся',
	cvar_log_file = 'Сохранять журнал в файлы на диске',
	cvar_log_spawns = 'Журналировать создания',
	cvar_max_size = 'Размеры большого пропа',
	cvar_model_blacklist = 'Включить черный лист моделей',
	cvar_model_whitelist = 'Черный лист моделей является белым листом',
	cvar_no_clear_messages = 'Отключить сообщения про удаления энтити отключившихся игроков',
	cvar_no_rope_world = 'Предотвращать создание верёвок на карте',
	cvar_no_rope_world_weld = 'Сварка считается за верёвку',
	cvar_no_tool_fail_log = 'Отключить журналирование неудачного использование инструмента',
	cvar_no_tool_log = 'Отключить журналирование инструментов',
	cvar_no_tool_log_echo = 'Отключить вывод журнала в консоль',
	cvar_player_cant_punt = 'Отключить толкание гравипушки',
	cvar_prevent_explosions_crash = '[Эксперементально!] Предотвращать падение сервера от множества взрывов за короткий промежуток времени',
	cvar_prevent_explosions_crash_num = 'Максимальное количество взрывов за промежуток времени. Изменяйте на свой страх и риск',
	cvar_prevent_player_stuck = 'Предотвращать ловушки из пропов',
	cvar_prevent_prop_throw = 'Не давать игрокам швырять пропы физпушкой',
	cvar_prop_auto_ban = 'Включить автобан пропов',
	cvar_prop_auto_ban_size = 'Лимит размера',
	cvar_restrict_e2afunction = 'Включить Expression 2 Advanced функции ограничения',
	cvar_restrict_e2afunction_white = 'Expression 2 Advanced функции ограничения работают как белый лист',
	cvar_restrict_e2afunction_white_bypass = 'Админы могут обойти белый лист Expression 2 Advanced функции (вызывать функции вне листа)',
	cvar_restrict_e2function = 'Включить Expression 2 функции ограничения',
	cvar_restrict_e2function_white = 'Expression 2 функции ограничения работают как белый лист',
	cvar_restrict_e2function_white_bypass = 'Админы могут обойти белый лист Expression 2 функции (вызывать функции вне листа)',
	cvar_restrict_model = 'Включить ограничения моделей',
	cvar_restrict_model_white = 'Ограничения моделей работают как белый лист',
	cvar_restrict_model_white_bypass = 'Админы могут обойти белый лист моделей (спавнить модели вне листа)',
	cvar_restrict_npc = 'Включить NPC ограничения',
	cvar_restrict_npc_white = 'NPC ограничения работают как белый лист',
	cvar_restrict_npc_white_bypass = 'Админы могут обойти белый лист NPC (спавнить NPC вне листа)',
	cvar_restrict_pickup = 'Включить ограничения подбираемых',
	cvar_restrict_pickup_white = '"подбираемые" ограничения работают как белый лист',
	cvar_restrict_pickup_white_bypass = 'Админы могут обойти белый лист "подбираемые" (подбирать энтити вне листа))',
	cvar_restrict_property = 'Включить ограничения свойств',
	cvar_restrict_property_white = 'Ограничения свойств работают как белый лист',
	cvar_restrict_property_white_bypass = 'Админы могут обойти белый лист свойств (использовать свойства вне листа)',
	cvar_restrict_sent = 'Включить ограничения энтити',
	cvar_restrict_sent_white = 'Ограничения энтити работают как белый лист',
	cvar_restrict_sent_white_bypass = 'Админы могут обойти белый лист "Энтити" (спавнить энтити вне листа)',
	cvar_restrict_swep = 'Включить ограничения оружия',
	cvar_restrict_swep_white = 'Ограничения оружия работают как белый лист',
	cvar_restrict_swep_white_bypass = 'Админы могут обойти белый лист оружия (спавнить оружия вне листа)',
	cvar_restrict_tool = 'Включить ограничения режимов инструмента',
	cvar_restrict_tool_white = 'Ограничения режимов инструмента работают как белый лист',
	cvar_restrict_tool_white_bypass = 'Админы могут обойти белый лист режимов инструмента (использовать инструменты вне листа)',
	cvar_restrict_vehicle = 'Включить ограничения транспорта',
	cvar_restrict_vehicle_white = 'Ограничения транспорта работают как белый лист',
	cvar_restrict_vehicle_white_bypass = 'Админы могут обойти белый лист транспорта (спавнить транспорт вне листа)',
	cvar_sbox_limits_enable = 'Включить лист лимитов SandBox',
	cvar_spawn_checks_noaspam = 'Отключить проверку на спам на всех энтити которые были обнаружены путём продвинутой проверки (рекомендуется)',
	cvar_strict_property = '[Эксперементально!] Включить строгую защиту свойств',
	cvar_strict_spawn_checks = '[Бета] (Очень) Строгие проверки на спавн',
	cvar_stuck_ignore_frozen = 'Не учитывать замороженные энтити при проверке "проп в пропе"',
	cvar_toolgun_player = 'Не разрешать использовать инструменты на игроках',
	cvar_toolgun_player_admin = 'Не разрешать использовать инструменты на игроках админам',
	cvar_unfreeze_antispam = 'Предотвращать спам размораживания физпушкой',
	cvar_unfreeze_antispam_delay = 'Минимальная задержка перед попытками разморозить',
	cvar_unfreeze_restrict = 'Ограничить разморозку физпушкой',
	cvar_unfreeze_restrict_num = 'Максимумальное количество энтити которое можно разморозить за раз',
	cvar_verbose_logging = 'Журналировать всёвозможные создания',
	cvar_whitelist_damage = 'Включить лист исключений урона',
	cvar_whitelist_gravgun = 'Включить лист исключений гравипушки',
	cvar_whitelist_physgun = 'Включить лист исключений физпушки',
	cvar_whitelist_pickup = 'Включить лист исключений подбираемых',
	cvar_whitelist_property = 'Включить лист исключений свойств',
	cvar_whitelist_propertyt = 'Включить лист исключений классов свойств',
	cvar_whitelist_tool = 'Включить лист исключений инструментов',
	cvar_whitelist_toolmode = 'Включить лист исключений режимов инструментов',
	cvar_whitelist_use = 'Включить лист исключений используемых',
	
	--Options
	sharing = 'Шаринг %s',
	unshare = 'Снять все галочки и применить',
	
	remove_my_ents = 'Удалить собственные энтити',
	display_customization_color = 'Настройка цвета отображения',
	display_customization = 'Настройки отображения',
	display_x = 'X координата (процент) на экране для позиции отображения владельца',
	display_y = 'Y координата (процент) на экране для позиции отображения владельца',
	
	clear_decals = 'Очистить декали',
	report_ents = 'Подсчитать и вывести статистику о энтити на карте',
	delete_ents = 'Удалить энтити игроков',
	
	freeze_all = 'Заморозить все физические объекты игроков',
	freeze_all_phys = 'Заморозить все физические объекты',
	delete_disconnected = 'Удалить энтити отключившихся игроков',
	action_unfreeze = 'Р',
	action_freeze = 'З',
	action_delete = 'У',
	fallback_select = 'Выбранный игрок: %s\nSteamID: %s',
	fallback_select_none = 'Выбранный игрок: <Нет>\n',
	owning_fallback = 'Эта страница отвечает за настройку "наследства"\nКогда Вы выходите с сервера, все ваши энтити передаются\nуказанному игроку',
	owning_fallback_r = 'Отменить выбор',
	disable_protection_for = 'Отключить защиту типа %q для %s',
	clipboard = 'Скопировать %s в буфер обмена',
	model_path = 'путь модели',
	Unblock = 'Разблокировать',
	model_blacklist = 'Черный лист Моделей',
	model_blacklist_2 = 'Черный лист Моделей. Что бы открыть меню модели, нажмите на её иконку.',
	Resizeable = 'Динамичный размер окна',
	click_reset = 'Нажмите тут чтобы сбросить размер окна',
	remove_from_blacklist = 'Удалить из чёрного листа',
	Class = 'Класс',
	Group = 'Группа',
	Groups = 'Группы',
	Limit = 'Лимит',
	Entity = 'Энтити',
	tool_mode = 'режим инструмента',
	add_tool_mode = 'Добавить режим инструмента',
	remove_tool_mode = 'Удалить режим инструмента',
	property_types_edit = 'Редактор DPP проперти',
	add_to_all_blacklists = 'Добавить это энтити во ВСЕ черные листы',
	add_to_all_blacklists_this = 'Добавить данное энтити во ВСЕ черные листы',
	remove_from_all_blacklists = 'Убрать это энтити во ВСЕ черные листы',
	remove_from_all_blacklists_this = 'Убрать данное энтити во ВСЕ черные листы',
	edit_limit = 'Добавить/Изменить лимит',
	edit_limit_a = 'Добавить/Изменить/Убрать лимит',
	edit_limit_e = 'Изменить лимит...',
	remove_limit = 'Убрать лимит',
	remove_limit_all = 'Убрать этот лимит для всех групп',
	entity_limit_note = 'ВНИМАНИЕ: Этот лист просто запрещает спавнить энтити\nс указанном классом выше этого лимита\nЭто означает, что это НЕ РАЗРЕШАЕТ спавнить группе\nнеограниченное количество энтити с данным классом.\nДля этого используйте лимиты "песочницы".',
	limit_tip = 'Неограниченно: -1\n0 - удаляет лимит из базы данных\nВсе значения больше 0 являются лимитом',
	elimit_tip = '-1 - удаляет лимит с базы данных\nЛюбое значение, включая 0, является лимитом',
	sbox_limit_note = 'ЧТО ЭТО ДЕЛАЕТ:\nЭто устанавливает значение sbox_max<...> для определённой группы.\nЧто-бы добавлять числа, Вам нужно знать, какие переменные вы хоотите изменить.\nПример: Изменения лимита пропов - "props" (sbox_maxprops).\nЗначение -1 - неограниченно, 0 - убирает уникальный лимит с группы, всё больше 0 устанавливает лимит.',
	constraints_limit_tip = 'Вы можете посмотреть типы соединений в логах DPP\nВНИМАНИЕ: Из-за того, как веревки сделаны\nDPP думает, что keyframe_rope является "vrope"\nпо причине того, что инструмент "верёвка" (и другие) создают энтити\nkeyframe_rope для визуальной верёвки.',
	sbox_max = 'sbox_max...',
	remove_from_restrict_list = 'Убрать из ограничительного листа',
	modify_r = 'Изменить...',
	add_r = 'Добавить...',
	edit_r = 'Изменить...',
	remove_friend = 'Удалить друга',
	add_friend = 'Добавить %s в список друзей',
	nick = 'Ник',
	steamid = 'SteamID',
	add_steamid = 'Добавить по SteamID',
	cvar_name = 'имя консольной переменной',
	add_entity = 'Добавить энтити',
	remove_entity = 'Убрать энтити',
	add_blacklist_looking_at = 'Добавить энтити на которое вы смотрите в черный лист',
	add_blacklist_looking_at_all = 'Добавить энтити на которое вы смотрите во ВСЕ черные листы',
	remove_blacklist_looking_at = 'Удалить энтити на которое вы смотрите из черного листа',
	remove_blacklist_looking_at_all = 'Удалить энтити на которое вы смотрите из ВСЕХ черных листов',
	is_white = 'Является белым листом',
	about_header = 'DPP был создан DBot\nДаный PP - попытка создать комбайнер который подходит для всех серверов,\nкоторые нуждаются в защите от мингов.\nАлсота помощь по русскому не помешала бы ибо у меня трояк по русскому :c',
	about_thumbup = 'Можна бесплатный лайк, позя?\nПОЗЯ?!',
	about_star = 'Можна бесплатную звезду, позя?\nПОЗЯ?!',
	about_bug = 'Можна бесплатный баг репорт, позя?\nПОЗЯ?!',
	about_issues = 'Страница ошибок DPP',
	display_customization_colors = 'Настройка цветов отображения',
	
	remove_exclude = 'Убрать из листа исключений',
	add_exclude_all = 'Добавить энтити во ВСЕ листы исключений',
	remove_exclude_all = 'Удалить энтити из ВСЕХ листов исключений',
	
	add_exclude_looking_at = 'Добавить энтити на которое вы смотрите в лист исключений',
	add_exclude_looking_at_all = 'Добавить энтити на которое вы смотрите во ВСЕ листы исключений',
	remove_exclude_looking_at = 'Убрать энтити на которое вы смотрите в лист исключений',
	remove_exclude_looking_at_all = 'Убрать энтити на которое вы смотрите во ВСЕ листы исключений',
	
	toolmode_exclude_tip = [[
Этот лист устанавливает, какие режимы инструмента
можно использовать на ЛЮБОМ энтити. К примеру, если
добавить "remover" в данный лист, то любой игрок может
удалить любое энтити других игроков с помощью инструмента.
ПОМНИТЕ: Черные листы ВСЕГДА выше всех и вся, поэтому, если
энтити будет в чёрном листе для инструмента, на нём всё равно
нельзя будет использовать режимы инструмента из данного листа.
]],

	exclude_tip = [[
Этот лист устанавливает, какие энтити не будут защищены
в режиме типа %q. К примеру, если
добавить "gmod_balloon" в данный лист, то любой игрок может
использовать данное энтити других игроков в режиме %q.
ПОМНИТЕ: Черные листы ВСЕГДА выше всех и вся, поэтому, если
энтити будет в чёрном листе, его всё равно нельзя будет использовать
в режиме %q.
]],

	property_exclude_tip = [[
Этот лист устанавливает, какие режимы свойств
можно использовать на ЛЮБОМ энтити. К примеру, если
добавить "remover" в данный лист, то любой игрок может
удалить любое энтити других игроков с помощью меню свойств.
ПОМНИТЕ: Черные листы ВСЕГДА выше всех и вся, поэтому, если
энтити будет в чёрном листе для инструментов, на нём всё равно
нельзя будет использовать свойство из данного листа.
]],

	properties_list = 'Открыть меню свойств...',
	property_class = 'Класс свойства',
	add_property = 'Добавить свойство',
	remove_property = 'Убрать свойство',
	tool_exclude = '\nПРИМЕЧАНИЕ: "remover" всё равно не может быть использован\nна энтити в данном листе',
	
	--Core messages
	model_is_blacklisted = 'Модель в чёрном списке',
	is_shared = 'Зашарено в режиме %q',
	is_shared_e = 'Зашарено',
	not_a_owner_pp = 'Не является владельцом/соединено',
	world_pp = 'Принадлежит/Привязано к миру',
	dpp_no_touch_true = 'dpp_no_touch = TRUE!',
	dpp_no_touch_world = 'dpp_no_touch_world = TRUE!',
	protection_disabled_owner = 'Владелец отключил %q защиту',
	dpp_no_touch_other = 'dpp_no_touch_other = TRUE!',
	protection_disabled = 'Защита отключена',
	World = 'Мир',
	not_valid = 'Энтити не является правильным',
	props_cleared = "%s's пропы были удалены",
	props_up_for_grabs = "%s's пропы теперь могут быт присвоены!",
	disconnected_player = 'Отключившийся игрок',
	up_for_grabs = 'Можно присвоить!',
	
	--Hooks messages
	owned_by_world = 'Нет владельца',
	no_toolgun_player = 'Нельзя использовать на игроке',
	entity_excluded = 'Энтити исключено по списку',
	entity_excluded_d = 'Урон разрешён (исключено)',
	toolmode_excluded = 'Режим в списке исключений',
	toolmode_blocked_world = 'Режим в чёрном списке "по миру"',
	toolgun_blocked = 'Инструмент заблокирован',
	no_rope_world = 'Нет верёвок по миру',
	restricted_tool = 'Ограниченный инструмент',
	vehicle_protection_ignored = 'Защита игнорируется',
	dpp_property = 'DPP свойство',
	property_restricted = 'Свойство ограничено',
	property_excluded = 'Свойство в списке исключений',
	use_blocked = 'Использование заблокировано',
	gravgun_blocked = 'Гравипушка заблокирована',
	physgun_blocked = 'Физпушка заблокирована',
	toolgun_antispam = 'Спам инструментом',
	damage_allowed = 'Урон разрешён',
	damage_blocked = 'Урон заблокирован',
	
	e2adv_func_restricted_s = '(СЕРВЕРНАЯ СТОРОНА) DPP: Функция ограничена: %s()',
	e2adv_func_restricted = 'DPP: Функция ограничена: %s()',
	
	--Server hooks messages
	unable_to_unfreeze = 'Невозможно размрозить: Вы пытаетесь разморозить %s энтити (%s максимум)!',
	physgun_reload_disabled = 'Pазморозка таким способом отключена на сервере',
	physgun_reload_wait = 'Вы должны подождать ещё %s секунд преджде чем попробовать снова',
	
	e2_func_restricted = 'DPP: Функция ограничена: %s()',
	spam_removed = 'Проп стал призраком из-за спама',
	spam_ghosted = 'Проп был удалён из-за спама',
	
	vehicle_restricted = 'Машина ограничена',
	model_restricted = 'Модель ограничена',
	weapon_restricted = 'Оружие ограничено',
	npc_restricted = 'NPC ограничено',
	entity_restricted = 'Энтити огранично',
	entity_limit_hit = 'Вы достигли лимит %q!',
	
	--Serverside functions
	ghosted_big = 'Проп стал призраком из-за его размеров.',
	prop_autoban = 'Проп слишком большой для тебя.',
	stuck_hit = 'Возможно, Ваш проп застрял в другом пропе.',
	grabs_hit = 'Теперь вы владелец этого пропа',
	
	limit_action = 'Добавить/Изменить/Удалить лимит',
	not_a_owner = 'Не является владельцем',
	
	--Report
	report_summary = '------------ ИТОГО',
	report_owners = '------------ ВЛАДЕЛЬЦЫ',
	report_spawned = ' имеет %s созданных энтити!',
	report_spawned_h = '------------ СОЗДАННЫЕ ЭНТИТИ ------------',
	report_allents = '------------ ВСЕ ЭНТИТИ ------------',
	report_allpos = '------------ ВСЕ ПОЗИЦИИ',
	report_allclass = '------------ ВСЕ КЛАССЫ',
	report_solidpos = '------------ ПОЗИЦИИ ТВЁРДЫХ ЭНТИТИ',
	report_solidclass = '------------ КЛАССЫ ТВЁРДЫХ ЭНТИТИ',
	report_misc = '------------ РАЗНОЕ',
	report_generated = '------------ ОТЧЁТ СОБРАН ЗА %s мс',
	report_envshake = 'ВНИМАНИЕ! На карте присутсвует %s env_shake энтити! Возможно, это утчека в одном из аддонов?',
	report_nodata = '<нет данных>',
	report_near = 'Около %s, тут ',
	report_have = ' имеет ',
	report_espawned = ' энтити создано!',
	report_entitites = ' энтити!',
	
	report_1 = 'Всего энтити on server:',
	report_2 = 'Всего созданных энтити:',
	report_3 = 'Всего энтити без владельца:',
	report_4 = 'Всего не-твёрдых энтити:',
	report_5 = 'Всего энтити созданных картой:',
	report_6 = 'Всего энтити с физикой:',
	report_7 = 'Всего энтити которые могут двигатся:',
	report_8 = 'Всего энтити которые двигаются:',
	report_9 = 'Энтити пропущено:',
	
	--Logging
	log_spawned = ' создал ',
	log_tried = ' попытался ',
	log_tried_c = 'создать соединение ',
	log_tried_f = 'использовать E2 функцию %s',
	log_to_spawn = 'создать',
	log_created_constraint = ' создал соединение ',
	log_constraint_between = ' между %s и %s',
	log_unknown = '<неизвестно>',
	
	log_tried_t = 'использовать инструмент  ',
	log_tool_used = ' использовал/попытался использовать инструмент ',
	log_tool_on = ' на ',
	log_tool_on_f = '%s на %s',
	
	log_not_avaliable = 'Н/Д',
	log_npc = '(NPC)',
	log_effect = '(Эффект)',
	log_prop = '(Проп)',
	log_ragdoll = '(Рэгдолл)',
	log_sent = '(Энтити)',
	log_swep = '(Оружие)',
	log_vehicle = '(Транспорт)',
	log_obj = '(Объект/Общее)',
	
	--Commands
	com_decals = ' очистил декали',
	com_no_target = 'Не найдено подходящей цели',
	com_invalid_target = 'Неверная цель',
	com_invalid_mode = 'Неверный режим',
	com_invalid_status = 'Неверный статус',
	com_invalid_pmode = 'Неверный режим защиты',
	com_invalid_uid = 'Неверный уникальный индетификатор игрока',
	com_invalid_eid = 'Неверный сетевой индетификатор энтити',
	com_invalid_ply_userid = 'Неверный UserID',
	com_invalid_ply_c = 'Неверный UserID/Ник',
	com_invalid_share = 'Неверный режим шары',
	com_invalid_cvar = 'Переменная сервера не существует',
	com_invalid_cvar_v = 'Неверное значение',
	com_cleared_disconnected = ' очистил энтити всех отключившихся игроков',
	com_cleared_map = ' очистил карту',
	com_cleared_ply_1 = ' очистил все ',
	com_cleared_ply_2 = "'s пропы",
	com_ply_ents = "'s энтити",
	com_freezed_players = " заморозил энтити всех игроков",
	com_freezed = ' заморозил все физические энтити. Всего заморожено: %s',
	com_freezed_all = ' заморозил все ',
	com_unfreezed_all = ' разморозил всё ',
	com_clear_success = 'Ваши энтити успешно удалены',
	com_clear_success_c = ' удалил все его энтити',
	com_transfer = ' передал права на ',
	com_transfer_s = 'Успешно передал права на проп миру',
	com_transfer_s_c = 'Успешно передал права на проп и всех соединенных с ним пропов миру',
	com_transfer_world = ' миру',
	com_transfer_world_c = ' со всеми соединёнными энтити миру',
	com_report_req = ' запросил отчёт об энтити',
	com_target = ' цель ',
	com_no_props_to_transfer = 'Нет энтити для передачи',
	com_transfer_all = ' передал права на все свои энтити ',
	com_owning_transfer = 'Права на энтити успешно переданы ',
	com_owning_transfer_all = 'Права на все Ваши энтити успешно переданы ',
	com_owning_fallback = ' как наследника его энтити',
	com_owning_fallback_m = ' теперь будет вашим наследником по пропам',
	com_owning_no = 'Уже нет никаких наследников',
	com_owning_removed_n = 'Наследник убран',
	com_owning_removed = ' убрал своего наследника по пропам.',
	com_success = 'Успех. ',
	com_fallback_triggered = 'Передаю права на все пропы игроку ',
	com_fallback_triggered_1 = 'Все ',
	com_fallback_triggered_2 = ' пропы теперь принадлежат Вам.',
	com_to = ' <цели/ему/к/на> ',
	com_cvar_set_1 = ' установил переменную ',
	look_into_console = 'Посмотрите в свою консоль разработчика',
	
	--Client commands
	no_friend_with_steamid = 'Нет друзей с ID %s!',
	friend_removed = 'Друг %s удалён',
	friend_added = 'Друг добавлен',
	friends_saved = 'Список друзей сохранён...',
	friends_loaded = 'Список друзей загружен...',
	friends_refreshed = 'Список друзей обновлён',
	friends_sended = 'Список друзей отправлен на сервер',
	
	--Property menus
	property_cleanup = 'Очистить энтити у владельца',
	property_share = 'Зашарить',
	property_transferworld = 'Передать права на проп миру',
	property_transferworld = 'Передать права на проп игроку...',
	property_roptions = 'Опции запрета DPP',
	property_add_blocked_models = 'Добавить в запрещённые модели',
	property_remove_blocked_models = 'Удалить из запрещённых моделей',
	property_add_blacklist = 'Добавить в %q DPP чёрный лист',
	property_remove_blacklist = 'Удалить из %q DPP чёрного листа',
	property_add_restrict = 'Добавить в %q DPP лист ограничений',
	property_remove_restrict = 'Удалить из %q DPP листа ограничений',
	property_modify_restrict = 'Изменить DPP %q ограничение...',
	
	--Misc messages
	prop_stuck_in_player = 'Ваш проп застрял в другом игроке',
	net_must_wait = 'Вы должны подождать прежде чем запрашивать полный пакет обновления сети снова!',
	net_manual = ' запросил полное обновления сети вручную',
	net_auto = ' запросил полное обновления сети автоматически',
	net_error_1 = 'О нет! Что-то пошло совсем не так! Я не могу отправить данные клиенту. Ошибка:',
	net_error_2 = 'Если вы думаете, что это ошибка в DPP, дайте мне знать, оставив тикет на баг трекере DPP на BitBucket, и, пожалуйста, расскажите как вы получили данную ошибку.',
	accepted = 'Принято',
	saving_cvars = 'Сохраняю значения переменных сервера в базу данных...',
	
	--Tool menu
	menu_server = 'Серверные переенные',
	menu_server2 = 'Вторичные серверные переменные',
	menu_propkill = 'Анти-Пропкил',
	menu_client = 'Клиентские настройки',
	menu_antispam = 'Настройки антиспама',
	menu_elimits = 'Лимиты энтити',
	menu_slimits = 'Лимиты Сандбокса',
	menu_climits = 'Лимиты соединений',
	menu_mblacklist = 'Чёрный лист моделей',
	menu_friends = 'Друзья',
	menu_players = 'Управление игроками',
	menu_pcontrols = 'Управление защитой игрокв',
	menu_about = 'О DPP',
	menu_fallback = 'Наследство и передача',
	menu_blacklist = '%q чёрный лист',
	menu_exclude = '%q лист исключений',
	menu_restricts = '%q ограничения',
	
	menu_tool = 'Инструменты',
	menu_physgun = 'Физган',
	menu_use = 'Использование',
	menu_damage = 'Урон',
	menu_gravgun = 'Гравипушка',
	menu_pickup = 'Подбирыемые',
	menu_toolworld = 'Инструмент на мире',
	menu_toolmode = 'Режимы Инструментов',
	menu_sent = 'Энтити',
	menu_vehicle = 'Транспорт',
	menu_swep = 'Оружие',
	menu_model = 'Модель',
	menu_npc = 'NPC',
	menu_property = 'Свойство',
	menu_propertyt = 'Класс свойства',
	menu_e2function = 'E2 Функции',
	menu_e2afunction = 'E2 Advanced Функции',
	
	menu_main = 'Основные настройки',
	menu_blacklists = 'Чёрные листы',
	menu_exclude_lists = 'Листы исключений',
	menu_restrictions = 'Ограничения',
	
	menu_player_tip = 'Имя игрока: %s\nSteamID игрока: %s\nSteamID64 игрока: %s\nЯвляется ли вашим другом: %s',
	menu_player_list_tip = 'Имя игрока: %s\nSteamID игрока: %s\nSteamID64 игрока: %s',
	steam_profile = 'Профиль Steam',
	open = 'Открыть %s',
	quick_search = 'Быстрый поиск по имени игрока в списке друзей',
	search_placeholder = 'Поиск...',
	
	menu_set_fallbackto = 'Выбрать наследника - %s',
	menu_transferto = 'Передать ВСЕ свои энтити игроку %s',
	
	--Some texts
	main_note = 'DPP создан DBot\nВНИМАНИЕ - "Главный рубильник" отключает черные листы\nи защитные модули, но не ограничения.',
	strict_property_note = [[
В.Н.И.М.А.Н.И.Е: ДАННАЯ ОПЦИЯ МОЖЕТ НЕ РАБОТАТЬ С
НЕ СТАНДАРТНЫМИ СВОЙСТВАМИ ОБЪЕКТОВ, ТАК КАК ОНА
ПОДМЕНЯЕТ ОБРАБОТКУ СЕТЕВЫХ СООБЩЕНИЙ СВОЙСТВ.
ИСПОЛЬЗУЙТЕ НА СВОЙ СТРАХ И РИСК. ВЫ БЫЛИ ПРЕДУПРЕЖДЕНЫ.
(может закрыть возможные уязвимости в нестандартных свойствах)
]],

	--Priveleges
	priv_addblockedentitydamage = 'Может добавлять запрещенные к урону энтити',
	priv_addblockedentitygravgun = 'Может добавлять запрещённые к гравипушке энтити',
	priv_addblockedentityphysgun = 'Может добавлять запрещённые к физпушке энтити',
	priv_addblockedentitypickup = 'Может добавлять запрещённые подбираемые энтити',
	priv_addblockedentitytool = 'Может добавлять запрещённые к использованию инструментами энтити',
	priv_addblockedentitytoolworld = 'Может добавлять запрещённые к запрещенным к использованию на мире режимов инструментов',
	priv_addblockedentityuse = 'Может добавлять запрещённые используемые энтити',
	priv_addblockedmodel = 'Может добавлять запрещенные модели',
	priv_addconstlimit = 'Может добавлять лимит соединений',
	priv_addentitylimit = 'Может добавлять лимит энтити',
	priv_addsboxlimit = 'Может добавлять лимит песочницы',
	priv_addwhitelistedentitydamage = 'Может добавлять в лист исключений по урону',
	priv_addwhitelistedentitygravgun = 'Может добавлять в лист исключений по гравипушке',
	priv_addwhitelistedentityphysgun = 'Может добавлять в лист исключений по физпушке',
	priv_addwhitelistedentitypickup = 'Может добавлять в лист исключений по подбираемым энтити',
	priv_addwhitelistedentityproperty = 'Может добавлять в лист исключений по свойствам',
	priv_addwhitelistedentitypropertyt = 'Может добавлять в лист исключений по классом свойств',
	priv_addwhitelistedentitytool = 'Может добавлять в лист исключений по инструментам',
	priv_addwhitelistedentitytoolmode = 'Может добавлять в лист исключений по режимам инструмента',
	priv_addwhitelistedentityuse = 'Может добавлять в лист исключений по используемым энтити',
	priv_clearbyuid = 'Может ли удалть энтити других игроков',
	priv_cleardecals = 'Может ли чистить декали',
	priv_cleardisconnected = 'Может ли очистить энтити отключившихся игроков',
	priv_clearmap = 'Может ли очищать карту',
	priv_clearplayer = 'Может ли удалять энтити других игроков',
	priv_clearself = 'Может ли чистить собственные жнтити',
	priv_entcheck = 'Может ли запрашивать отчёт об энтити на карте',
	priv_fallbackto = 'Может ли устанавливать наследство',
	priv_freezeall = 'Может ли замораживать все физические объекты',
	priv_freezebyuid = 'Может ли замораживать энтити игрока по уникальному индетификатору',
	priv_freezeplayer = 'Может ли замораживать энтити других игроков',
	priv_removeblockedentitydamage = 'Может убирать запрещённые к урону энтити',
	priv_removeblockedentitygravgun = 'Может убирать запрещённые к гравипушке энтити',
	priv_removeblockedentityphysgun = 'Может убирать запрещённые к физпушке энтити',
	priv_removeblockedentitypickup = 'Может убирать запрещённые к подбираемым энтити',
	priv_removeblockedentitytool = 'Может убирать запрещённые к использованию инструментами энтити',
	priv_removeblockedentitytoolworld = 'Может убирать запрещённые к использованию режимов инструментов на мире',
	priv_removeblockedentityuse = 'Может убирать запрещённые к использованию энтити',
	priv_removeblockedmodel = 'Может убирать запрещённые модели',
	priv_removeconstlimit = 'Может убирать лимиты соединений',
	priv_removeentitylimit = 'Может ли убирать лимиты на энтити',
	priv_removefallbackto = 'Может ли убирать игрока наследника',
	priv_removesboxlimit = 'Может ли убирать лимиты песочницы',
	priv_removewhitelistedentitydamage = 'Может убирать из листа исключений по урону',
	priv_removewhitelistedentitygravgun = 'Может убирать из листа исключений гравипушки',
	priv_removewhitelistedentityphysgun = 'Может убирать из листа исключений физпушки',
	priv_removewhitelistedentitypickup = 'Может убирать из листа исключений подбираемых энтити',
	priv_removewhitelistedentityproperty = 'Может убирать из листа исключений по свойствам',
	priv_removewhitelistedentitypropertyt = 'Может убирать из листа исключений по классам свойств',
	priv_removewhitelistedentitytool = 'Может убирать из листа исключений по использованию инструментов на энтити',
	priv_removewhitelistedentitytoolmode = 'Может убирать из листа исключений по режимам инструментов',
	priv_removewhitelistedentityuse = 'Может убирать из листа исключений используемых энтити',
	priv_restricte2afunction = 'Может добавлять функции в лист ограничений E2 Advanced',
	priv_restricte2function = 'Может добавлять функции в лист ограничений E2',
	priv_restrictmodel = 'Может добавлять модели в лист ограничений',
	priv_restrictnpc = 'Может добавлять NPC в лист ограничений',
	priv_restrictpickup = 'Может добавлять поднимаемые энтити в лист ограничений',
	priv_restrictproperty = 'Может добавлять свойства в лист ограничений',
	priv_restrictsent = 'Может добавлять энтити в лист ограничений',
	priv_restrictswep = 'Может добавлять оружия в лист ограничений',
	priv_restricttool = 'Может добавлять режимы инструментов в лист ограничений',
	priv_restrictvehicle = 'Может добавлять транспорт в лист ограничений',
	priv_seelogs = 'Может ли игрок видеть журнал',
	priv_setvar = 'Может ли игрок менять переменные DPP',
	priv_share = 'Может ли шарить энтити',
	priv_toggleplayerprotect = 'Может ли менять статус защиты для других игроков',
	priv_touchother = 'Может ли трогать энтити других игроков',
	priv_transfertoplayer = 'Может ли передавать энтити другим игрокам',
	priv_transfertoplayer_all = 'Может ли передавать все энтити другим игрокам',
	priv_transfertoworld = 'Может ли передавать энтити миру',
	priv_transfertoworld_constrained = 'Может ли передавать энтити миру со всеми соединенными энтити',
	priv_unfreezebyuid = 'Может ли разморозить энтити других игроков используя уникальный индетификатор',
	priv_unfreezeplayer = 'Может ли разморозить энтити других игроков',
	priv_unrestricte2afunction = 'Может убирать функции из листа ограничений E2 Advanced',
	priv_unrestricte2function = 'Может убирать функции из листа ограничений E2',
	priv_unrestrictmodel = 'Может убирать модели из листа ограничений',
	priv_unrestrictnpc = 'Может убирать NPC из листа ограничений',
	priv_unrestrictpickup = 'Может убирать поднимаемые энтити из листа ограничений',
	priv_unrestrictproperty = 'Может убирать свойства из листа ограничений',
	priv_unrestrictsent = 'Может убирать энтити из листа ограничений',
	priv_unrestrictswep = 'Может убирать оружия из листа ограничений',
	priv_unrestricttool = 'Может убирать режимы инструментов из листа ограничений',
	priv_unrestrictvehicle = 'Может убирать транспорт из листа ограничений',
	
	givechance_error = 'ВНИМАНИЕ! ЭНТИТИ БРОСИЛО ИСКЛЮЧЕНИЕ. ',
	givechance_Entity = 'Энтити ',
	givechance_desc = ' БРОСИЛО СЛЕДУЮЩЕЕ ИСКЛЮЧЕНИЕ ВО ВРЕМЯ ВЫЗОВА %q: ',
	givechance_returned = 'Энтити управляет своей защитой',
	
	Console = 'Сервер',
	request_net_update = 'Запросить обновление сети DPP',
	
	--Manipulation commands
	saveload_added = ' добавил ',
	saveload_removed = ' убрал ',
	saveload_to = ' в ',
	saveload_from = ' из ',
	saveload_bmodels = ' чёрный лист моделей',
	saveload_invalid_model = 'Неверная модель',
	saveload_invalid_class = 'Неверный класс энтити',
	saveload_invalid_group = 'Неверная группа',
	saveload_invalid_limit = 'Неверное цифровое значение',
	saveload_invalid_slimit = 'Неверное название переменной',
	saveload_invalid_climit = 'Неверное название соединения',
	saveload_model_already_y = 'Модель уже заблокирована',
	saveload_entity_already_y = 'Энтити уже заблокировано',
	saveload_eentity_already_y = 'Энтити уже в списке исключений',
	saveload_model_already_n = 'Модель не заблокирована',
	saveload_entity_already_n = 'Энтити не заблокировано',
	saveload_eentity_already_n = 'Энтити не находится в списке исключений',
	saveload_unable_to_add = 'Вы не можете добавить это энтити в данный список',
	saveload_unable_to_remove = 'Вы не можете убрать это энтити из данного списока',
	saveload_blackwhite = ' чёрный/белый лист',
	saveload_excludedents = ' лист исключений',
	saveload_restricted = 'ограничил ',
	saveload_added_updated = ' добавил/изменил ',
	saveload_limit_removed = ' из листа лимитов для ',
	saveload_limits = ' лимиты для ',
	saveload_slimits = ' sandbox лимиты для ',
	saveload_climits = ' лимиты соединений для ',
	saveload_limit_not_exists = 'Лимит для данного класса не существует',
	
	saveload_command_message_1 = 'Неверный класс для ограничения (#1)',
	saveload_command_message_2 = 'Неверные групп(ы). Группы разделены запятой (,), без пробелов (#2)',
	saveload_command_message_3 = 'Неверный аргумент к "является белым листом" (#3)',
	saveload_command_message_4 = 'Неверный класс для убирания ограничения',
	
	menu_misc_moved = 'Общие кнопки были перемещены в "Утилиты"',
	utilities = 'Утилиты',
	
	inspect_button = 'Проверить энтити на которое Вы смотрите',
	inspect_client = '--КЛИЕНТ--',
	inspect_server = '--СЕРВЕР--',
	inspect_class = 'Класс Энтити: ',
	inspect_pos = 'Позиция Энтити: ',
	inspect_ang = 'Углы Энтити: ',
	inspect_hp = 'Здоровье Энтити: ',
	inspect_mhp = 'Максимальное Здоровье Энтити: ',
	inspect_owner = 'Владелец Энтити: ',
	inspect_model = 'Модель Энтити: ',
	inspect_skin = 'Скин Энтити: ',
	inspect_bodygroups = 'Количество изменяемых частей Энтити: ',
	inspect_table = 'Количество записей в :GetTable() Энтити:',
	inspect_noentity = 'Неверное Энтити',
	
	block_damage = 'Урон',
	block_gravgun = 'Гравипушка',
	block_physgun = 'Физпушка',
	block_pickup = 'Подбираемые',
	block_tool = 'Инструмент',
	block_toolworld = 'Режим инструмента по миру',
	block_use = 'Используемые',
	cvar_prop_auto_ban_check_aabb = 'Проверять AABB размер',
	cvar_prop_auto_ban_minsmaxs = 'Маскимальная дистанция между минимальным и максимальным векторами коробки столкновений',
	exclude_damage = 'Урон',
	exclude_gravgun = 'Гравипушка',
	exclude_physgun = 'Физпушка',
	exclude_pickup = 'Подбираемые',
	exclude_property = 'Свойство',
	exclude_propertyt = 'Тип Свойства',
	exclude_tool = 'Инструмент',
	exclude_toolmode = 'Режим инструмента',
	exclude_use = 'Используемые',
	priv_inspect = 'Может ли "опознать" энтити',
	property_transferplayer = 'Передать энтити игроку...',
	restricted_e2afunction = 'Expression 2 Advanced функция',
	restricted_e2function = 'Expression 2 функция',
	restricted_model = 'Модель',
	restricted_npc = 'NPC',
	restricted_pickup = 'Подбираемые',
	restricted_property = 'Свойство',
	restricted_sent = 'Энтити',
	restricted_swep = 'Оружие',
	restricted_vehicle = 'Транспорт',
	restricts_updated = '(БЕЗ ОПОВЕЩЕНИЙ ДРУГИМ) Вы обновили ограничения на %s',
	
	ccvar_disable_damage_protection = 'Отключить защиту от урона для моих энтити',
	ccvar_disable_gravgun_protection = 'Отключить защиту гравипушки для моих энтити',
	ccvar_disable_physgun_protection = 'Отключить защиту физпушки для моих энтити',
	ccvar_disable_toolgun_protection = 'Отключить защиту от инструментов для моих энтити',
	ccvar_disable_use_protection = 'Отключить защиту используемых для моих энтити',
	ccvar_disable_vehicle_protection = 'Отключить защиту моего транспорта ',
	ccvar_display_disconnected = 'Отображать отключился ли владелец энтити',
	ccvar_display_entityclass = 'Отображать класс энтити',
	ccvar_display_entityclass2 = 'Отображть сетевой индетификатор и сетевой класс энтити',
	ccvar_display_entityname = 'Отображать имя энтити',
	ccvar_display_grabs = 'Отображать, можно ли присвоить энтити',
	ccvar_display_owner = 'Отображать владельца энтити',
	ccvar_display_reason = 'Отображать причину возможности трогать энтити',
	ccvar_draw_in_screenshots = 'Отображать владельца на скриншотах',
	ccvar_font = 'Шрифт (1 для стандартного)',
	ccvar_hide_hud = 'Отключить отображение информации',
	ccvar_no_block_options = 'Отключить опции быстрого блокирования в меню свойств',
	ccvar_no_hud_in_vehicle = 'Отключить отображение пока в транспорте',
	ccvar_no_load_messages = 'Я не хочу видеть надписи про загрузку листов',
	ccvar_no_physgun_display = 'Отключить красивое отображения информации на физпушке',
	ccvar_no_player_touch = 'Я не хочу трогать других игроков (если администратор)',
	ccvar_no_restrict_options = 'Отключить опции быстрого ограничения в меню свойств',
	ccvar_no_scrambling_text = 'Отключить перемешивающийся текст',
	ccvar_no_toolgun_display = 'Отключить красивое отображения информации на инструменте',
	ccvar_no_touch = 'Я не хочу трогать энтити владелец которых - я',
	ccvar_no_touch_other = 'Я не хочу трогать энтити других игроков',
	ccvar_no_touch_world = 'Я не хочу трогать энтити принадлежащие карте',
	ccvar_simple_hud = 'Упрощённая панель владельца',
	ccvar_smaller_fonts = 'Использовать мелкие шрифты (работает только с шрифтами DPP)',
	cust_display_background = 'Фон информационной панели',
	cust_display_can = 'Цвет текста когда можно трогать',
	cust_display_cant = 'Цвет текста когда нельзя трогать',
	display_customization_position = 'Позиция панели',
	font = 'Шрифт',
	
	ccvar_disable_pickup_protection = 'Отключить защиту для подбираемых моих энтити',
	friend_buddy = 'Является другом в режиме %q',
	protmode_damage = 'Урон',
	protmode_gravgun = 'Гравипушка',
	protmode_physgun = 'Физпушка',
	protmode_pickup = 'Подбираемые',
	protmode_toolgun = 'Инструменты',
	protmode_use = 'Используемые',
	protmode_vehicle = 'Транспорт',
	share_type = 'Зашарить в режиме %q',

	cvar_strict_spawn_checks_atrack = '[ОБЖИГАЮЩЕ НЕСТАБИЛЬНО] Отслеживать таблицы энтити на изменения.\nЭто самый пик всех отслеживаний.\nЭТА ОПЦИЯ ЛОМАЕТ ЗАЩИТУ СОЕДИНЕННЫХ\nИНСТРУМЕНТОМ ЭНТИТИ. АКТИВИРУЙТЕ НА СВОЙ СТРАХ И РИСК',
	priv_freezephys = 'Может ли заморозить все физические объекты',
	
	crazy_physics = 'Обнаружен неверный физический объект: ',
	crazy_physics2 = ' который принадлежит ',
	crazy_physics3 = ', делаю объект призраком.',
	cvar_apropkill_crash = 'Пытатся предотвратить краш сервера от бесчисленной коллюзии пропов',
	cvar_log_spawns_model = 'Записывать модель энтити',
	cvar_log_spawns_nname = 'Записывать сетевой класс и ID энтити',
	cvar_log_spawns_pmodel = 'Записывать модели только у пропов',
	cvar_log_spawns_type = 'Записывать типь энтити',
	
	cami_tip = "Не можете найти свою группу?\nВы можете написать её тут!\n(обычно это случается когда модификация администрирования\nне поддерживает CAMI или её поддержка крайне плохая\nCAMI - Common Admin Mod Interface, Общий интерфейс модификации администрирования)",
}

DPP.RegisterPhraseList('en', en)
DPP.RegisterPhraseList('ru', ru)
